### ISSUE TITLE
[Hacktoberfest] Add more images

### ISSUE THREAD

**Issue by albertopoljak** [albertopoljak/orindance.party#3]
Add more party images to index.html

Orin (character) needs to be in image (or other Touhou characters doing party stuff) and image link should be permanent (not to become 404 after few months).

Edit: Don't forget the comma `,` when adding a new entry! 2 previous PRs both forgot them :D

**Comment by mukulgarg10** [comment]
Can you please assign this to me ?

**Comment by iamsandipanbera** [comment]
I would like to add

**Comment by albertopoljak** [comment]
Oh wow that was incredibly fast.

@iamsandipanbera @mukulgarg10 you are both free to open an PR which will be counted towards Hacktoberfest.
There is no need to assign one person as there could be multiple PRs.

**Comment by iamsandipanbera** [comment]
@albertopoljak Checkout PR #4

**Comment by HuyaneMatsu** [comment]
Can we close this issue? Hacktober is over TM

**Comment by albertopoljak** [comment]
@HuyaneMatsu alright, see you in 2 months
